version: '3.8'

services:
  backend:
    build:
      context: ./cc-webapp/backend
      dockerfile: Dockerfile
    volumes:
      - ./cc-webapp/backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://cc_user:cc_password@postgres:5432/cc_webapp
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=your_jwt_secret_key
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./cc-webapp/frontend
      dockerfile: Dockerfile
    volumes:
      - ./cc-webapp/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=cc_user
      - POSTGRES_PASSWORD=cc_password
      - POSTGRES_DB=cc_webapp

  redis:
    image: redis:7

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend

volumes:
  postgres_data: {}