version: '3.8'

services:
  backend:
    build:
      context: ./cc-webapp/backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://cc_user:cc_password@postgres:5432/cc_webapp
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=your_jwt_secret_key
      - API_SECRET_KEY=your_api_secret_key
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./cc-webapp/frontend
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "3000:3000"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=cc_user
      - POSTGRES_PASSWORD=cc_password
      - POSTGRES_DB=cc_webapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: